name: exam_score_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.7
  - pip
  - pip:
      - mlflow==2.19.0
      - dagshub
      - scikit-learn
      - pandas
      - matplotlib
      - seaborn
      - virtualenv